{
	"version": 1749399228,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-3.4.1.min.js",
		"offlineClient.js",
		"images/sprite-sheet0.png",
		"images/sprite2-sheet0.png",
		"images/sprite3-sheet0.png",
		"images/p1-sheet0.png",
		"images/p2-sheet0.png",
		"images/sprite6-sheet0.png",
		"images/marca-sheet0.png",
		"images/marca-sheet1.png",
		"images/clickhitbox-sheet0.png",
		"images/setatralalela-sheet0.png",
		"images/setatralalela-sheet1.png",
		"images/placa-sheet0.png",
		"images/icon-sheet0.png",
		"images/icon-sheet1.png",
		"images/placa_texto1.png",
		"media/lose_race.m4a",
		"media/lose_race.ogg",
		"media/beach bowl galaxy - super mario galaxy.m4a",
		"media/beach bowl galaxy - super mario galaxy.ogg",
		"media/4 - track 4.m4a",
		"media/4 - track 4.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}